### PR TITLE
Responsive design fixed #95

### LINKED ISSUE #95: Brand slider responsive design
Brand slider responsive design

### PR DESCRIPTION
**Pull request by bemze**
Brand slider linkai sukisti i atskira div su klase col-12, kad susitvarkytu resposive dizainas bendram projektui ir neluzinetu kiti dalykai.

Nieko nebuvo stailinta,

### CODE REVIEW

**Review by pigma15 — APPROVED** [review]
reiketu

**Review by pigma15 — CHANGES_REQUESTED** [review]
Maciau, kad Marius jau visai isibegejes su brand-logo, tad galim palaukti gal jo PR?

**Comment by bemze** [comment]
changed everywhere vw into % - fixed horizontal scroll bug

brand slider added extra div with class col-12 to fix temporary responsive design

**Comment by JRybelis** [comment]
The fix appears to have resolved the bug. LGTM

**Review by JRybelis — APPROVED** [review]

**Review by pigma15 — APPROVED** [review]
lgtm

**Pull request merged**
