### PR TITLE
Hero responsive

### PR DESCRIPTION
**Pull request by bemze**
Istrinus Brand Slider sekcija - responsive dizainas veikia pas mane grazai (mob versija ir t.t)

### CODE REVIEW

**Review by pigma15 — DISMISSED** [review]
Since nothing breaks and with this PR things look better - approve. However, after breakpoint of max-width: 860px everything should become centered in hero section.
Now:
image
Should be edited later

**Review by pigma15 — APPROVED** [review]
lgtm

**Review by JRybelis — APPROVED** [review]
lgtm

**Review by pigma15 — APPROVED** [review]
lOKtm

**Pull request merged**
