### PR TITLE
Our services section P tag fix

### PR DESCRIPTION
**Pull request by martynas3113**
Fixsed p tag text

### CODE REVIEW

**Review by pigma15 — APPROVED** [review]
lgtm

**Review by pigma15 — COMMENTED** [review]
noriu atskaukt approve :D

**Review by pigma15 — CHANGES_REQUESTED** [review]
Rodos, kad Jusu su Mantu PR kertasi

**Comment by bemze** [comment]
fix conflict

**Review by bemze — APPROVED** [review]
conflictas istaisytas

**Review by pigma15 — APPROVED** [review]
niekas nesuluzo

**Pull request merged**
